apiVersion: v1
kind: Service
metadata:
  name: {{ include "stellar-operator.fullname" . }}
  labels:
    {{- include "stellar-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.restApiPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "stellar-operator.selectorLabels" . | nindent 4 }}
