apiVersion: v2
name: stellar-operator
description: A Helm chart for the Stellar-K8s Kubernetes Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - stellar
  - kubernetes
  - operator
  - blockchain
  - soroban
maintainers:
  - name: Stellar K8s Contributors
    url: https://github.com/stellar/stellar-k8s
sources:
  - https://github.com/stellar/stellar-k8s
